application: Codemotionroma2014
version: 1
deploy: true
pub: true
dart2js: false
framework: dart

handlers:
- url: /test
  match: exact
  script: sample_server.dart

# Static content
- url: /
  match: postregex
  static_dir: web